### ISSUE TITLE
When I run your code  some error has occured

### ISSUE THREAD

**Issue by sshzhang** [librahu/MCRec#5]
my environment is Theano (1.0.1) , Keras (2.1.1)  ubuntu 16.04, here is the specific error
        Traceback (most recent call last):
  File "/home/zxj/PycharmProjects/MCRec/code/MCRec.py", line 495, in <module>
    model = get_model(num_users, num_items, path_nums, timestamps, length, layers, reg_layes, latent_dim, reg_latent)
  File "/home/zxj/PycharmProjects/MCRec/code/MCRec.py", line 267, in get_model
    umtm_latent = get_umtm_embedding(umtm_input, path_nums[0], timestamps[0], length, user_latent, item_latent, path_attention_layer_1, path_attention_layer_2)
  File "/home/zxj/PycharmProjects/MCRec/code/MCRec.py", line 103, in get_umtm_embedding
    output = Dropout(0.5)(output)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 117, in call
    training=training)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1503, in in_train_phase
    x = theano.ifelse.ifelse(training, x, alt)
AttributeError: 'module' object has no attribute 'ifelse'

I hope you can kindly help me solve this problems! Thank you very much!

**Comment by librahu** [comment]
Please update the following environment
tensorflow == 1.2.1
Theano == 1.0.1
Keras == 2.1.1

**Comment by sshzhang** [comment]
Thanks a lot ,  I solved it,  after reading your code,  I have a problem, Here is the specific description . 
 

![image](https://user-images.githubusercontent.com/17669403/50874272-61815e80-13fe-11e9-827e-cc9f50401689.png)

The weight matrix Wu(1) is the same for all user?    is it right ?  Thank you very much!

**Comment by librahu** [comment]
Yes, this expression may be confusing. The meaning of W_u^(1) is that the weight matrix of first layer for user, not for specific user u.
